lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

    api_platform:
        check_path: /login
        username_path: email
        password_path: password

    token_ttl: 7200

when@dev:
    lexik_jwt_authentication:
        token_ttl: 86400