controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /login
    methods: ['POST']

api_doc:
    path: /docs
    controller: api_platform.swagger_ui.action